# Describes the format for available services for bmw_connected_drive
#
# The services related to locking/unlocking are implemented in the lock
# component to avoid redundancy.

light_flash:
  description: >
    Flash the lights of the vehicle. The vehicle is identified via the VIN
    (see below).
  fields:
    vin:
      description: >
        The Vehicle Identification Number (VIN) of the vehicle, 17 characters.
        The VIN of your car can be found in the attributes of the device_tracker.
      example: WBANXXXXXX1234567

sound_horn:
  description: >
    Sound the horn of the vehicle. The vehicle is identified via the VIN
    (see below).
  fields:
    vin:
      description: >
        The Vehicle Identification Number (VIN) of the vehicle, 17 characters.
        The VIN of your car can be found in the attributes of the device_tracker.
      example: WBANXXXXXX1234567

activate_air_conditioning:
  description: >
    Start the air conditioning of the vehicle. What exactly is started here
    depends on the type of vehicle. It might range from just ventilation over
    auxiliary heating to real air conditioning. The vehicle is identified via
    the VIN (see below).
  fields:
    vin:
      description: >
        The Vehicle Identification Number (VIN) of the vehicle, 17 characters.
        The VIN of your car can be found in the attributes of the device_tracker.
      example: WBANXXXXXX1234567

send_message:
  description: >
    Send a message to the vehicle.
    The vehicle is identified via the VIN (see below).
  fields:
    vin:
      description: >
        The Vehicle Identification Number (VIN) of the vehicle, 17 characters.
        The VIN of your car can be found in the attributes of the device_tracker.
      example: WBANXXXXXX1234567
    text:
      description: >
        The text of the message.
      example: This is the text of the message, with a maximum of 255 characters.
    subject:
      description: >
        The subject of the message.
      example: Home Assistant

send_poi:
  description: >
    Send a Point of Interest (POI) to the vehicle.
    The vehicle is identified via the VIN (see below).
  fields:
    vin:
      description: >
        The Vehicle Identification Number (VIN) of the vehicle, 17 characters.
        The VIN of your car can be found in the attributes of the device_tracker.
      example: WBANXXXXXX1234567
    latitude:
      description: >
        The latitude of the coordinates you want to go to.
      example: 48.176988
    longitude:
      description: >
        The longitude of the coordinates you want to go to.
      example: 11.559140
    name:
      description: >
        The name of the place you want to go to (can be left empty).
      example: BMW Munich

update_state:
  description: >
    Fetch the last state of the vehicles of all your accounts from the BMW
    server. This does *not* trigger an update from the vehicle, it just gets
    the data from the BMW servers. This service does not require any attributes.
